### ISSUE TITLE
Issue downloading pptx, xlsx files

### ISSUE THREAD

**Issue by todhing** [viewvc/viewvc#128]
When using ViewVC 1.0.0 to download a powerpoint presentation or excel file, and then opening the file I only see garbage or raw data in the file.  I checked my /etc/mime.types file and the corresponding pptx and xlsx types are there.  I also increased the memory limit in my php.ini as suggested in another post.

I used an svn client to checkout the file, and was able to open the pptx and xlsx files cleanly.

Is there a way to confirm that the ViewVC is reading my /etc/mime.types files correctly?  Any other suggestions would be helpful.

**Comment by cmpilato** [comment]
ViewVC 1.0.0 is ancient, @todhing -- release 10 1/2 years ago!  The 1.0.x line is not even being maintained.  Are you stuck on that version for reasons outside your control, or are you able to upgrade to the latest 1.1.25?

**Comment by cmpilato** [comment]
Closing for lack of response.
