### ISSUE TITLE
Syntax highlighting in text/cmd files can throw proxy timeouts

### ISSUE THREAD

**Issue by ms-chr** [viewvc/viewvc#130]
Hi,

here is my environment:

ViewVC: 1.1.24 / 1.1.25
OS: SLES 11 SP4
Python: 2.6.9-39.1
Runs as a CGI program under a Apache web Server

If I have commit a file like this:

`
rem works not if syntax highlighting is on and mimetype ist text/cmd
 if %NotMoreCharsThen_hm_some_I_dont_no____WhoKnowThisTruely% LSS %bar% (
    del %foo2%
) 

rem rem works if syntax highlighting is on and mimetype ist text/cmd
rem  if %foo% LSS %bar% (
rem     del %foo2%
rem ) 
`

and try to show it in the web browser with viewvc, than I get a only a loading page....

Apache Error Log: 
[error] [client 'IP'] (70007)The timeout specified has expired: proxy: error reading status line from remote server 'server', referer: https://'server'/svn/'repo'/
[error] [client 'IP'] proxy: Error reading from remote server returned by /svn/'repo'/'path'/'file', referer: https://'server'/svn/'repo'/
[error] [client 'IP'] Script timed out before returning headers: viewvc.cgi, referer: https://'server'/svn/'repo'/

![viewvc](https://cloud.githubusercontent.com/assets/14216655/20628878/efaa3e4a-b328-11e6-9f89-e48e05e1c4e0.png)

If the variable is shorter %NotMoreCharsThen_hm_some_I_dont_no____WhoKnowThisTruely% like %foo%, no error happens.

**Comment by cmpilato** [comment]
I can confirm that there is, in fact, a problem with the way that Pygments handles your "doesn't work" scenario.  You can see this from the command-line, even:

    $ cat worksnot.bat 
    rem works not if syntax highlighting is on and mimetype is text/cmd
    if %NotMoreCharsThen_hm_some_I_dont_no____WhoKnowThisTruely% LSS %bar% (
    del %foo2%
    )
    $ pygmentize worksnot.bat 
    rem works not if syntax highlighting is on and mimetype is text/cmd

_(processing hangs before the completion of the syntax highlighting)_

Please report this issue to the Pygments community.  (Looks like https://bitbucket.org/birkenfeld/pygments-main/issues is where their issue tracker lives.)

**Comment by dscorbett** [comment]
FYI, I made [a pull request upstream](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/620/fix-batch-variables-after-if/diff) to fix this a few months ago. Pygments has an excruciatingly slow release cycle, so if this timeout issue is important, you might consider forking Pygments temporarily and merging the pull request yourselves.
