### ISSUE TITLE
make-database script does not sanitize input

### ISSUE THREAD

**Issue by anthonypants** [viewvc/viewvc#141]
```
$ sudo /usr/lib/python2.7/site-packages/viewvc/bin/make-database
MySQL Hostname (leave blank for default):
MySQL Port (leave blank for default):
MySQL User: viewvc
MySQL Password: 0gtJ)XcnQ!l3
ViewVC Database Name [default: ViewVC]: viewvc
/bin/sh: -c: line 0: syntax error near unexpected token `)'
/bin/sh: -c: line 0: `{ mysql --user=viewvc --password=0gtJ)XcnQ!l3 ; } 2>&1'

[ERROR] The database did not create sucessfully.
$
```

You can correct this by inserting your own punctuation (but you **really** shouldn't have to):

```
$ sudo /usr/lib/python2.7/site-packages/viewvc/bin/make-database
MySQL Hostname (leave blank for default):
MySQL Port (leave blank for default):
MySQL User: viewvc
MySQL Password: '0gtJ)XcnQ!l3'
ViewVC Database Name [default: ViewVC]: viewvc

Database created successfully.  Don't forget to configure the
[cvsdb] section of your viewvc.conf file.
$
```

**Comment by dev1098** [comment]
Similar issue with different result:

`[root@host bin]# ./make-database
./make-database:20: DeprecationWarning: The popen2 module is deprecated.  Use the subprocess module.
  import popen2
MySQL Hostname (leave blank for default):
MySQL Port (leave blank for default):
MySQL User: vcviewuser
MySQL Password: 'passwordwith!'
ViewVC Database Name [default: ViewVC]:
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1067 (42000) at line 14: Invalid default value for 'ci_when'

[ERROR] The database did not create sucessfully.
`

EL 6.9
Python 2.6.6
MySQL 5.7.18-1
ViewVC 1.1.26-1 (from EPEL)

**Comment by mind12** [comment]
I had the same problem as dev1098: `ERROR 1067 (42000) at line 14: Invalid default value for 'ci_when'`
I edited the make-database script and gave 'ci_when' a proper DEFAULT value. After that the database was created successfully.

**Comment by futatuki** [comment]
> (and I think it is better to use --defaults-file to pass password to mysql, but it may breaks compatibility for some old MySQL version and I can't make to test for it, so I don't touch for it)

I meant '--defaults-extra-file'  by '--defaults-file', for default setting files should be read. However I'm also afraid some old version of mysql command line clients are affected by bug https://bugs.mysql.com/bug.php?id=12917.

**Comment by cmpilato** [comment]
I've opened issue #200 for the `ci_when` concern.  Let's do keep that separate.

**Comment by cmpilato** [comment]
Also, I believe @futatuki 's pull request #198 addresses this issue.  That change has landed on `master` only, though.  I'm seriously considering bumping the minimal Python version requirement for `1.1.x` to allow me to backport and release that fix, there, too.
