### ISSUE TITLE
HTTPS not working 

### ISSUE THREAD

**Issue by did8** [viewvc/viewvc#152]
Hi All,

It seems like I cannot figure out how to configure HTTPS with ViewVC. All other sites that I am working on I had no issues with HTTPS configuration. ViewVC is the only one. 
I configured the VirtualHost in ssl.conf restarted httpd (i am using Centos 7). I have another site on the same server working with no issues.

Does ViewVC require additional configuration for HTTPS to work?

Let me know if you need more details.

**Comment by cmpilato** [comment]
ViewVC has no special needs as regards SSL. What exactly is the problem you are experiencing?

**Comment by did8** [comment]
Thank you for the reply. 
The issue is that i configured the virtualhost (the same config that is working for the other web server that i have on the same server). But i am still not able to access ViewVC over https. I configured that self signed SSL cert, confirmed that i can access https://192.168.10.20 and i can see the default apache welcome page. On the same server i have nagios installed and i can access it with no issues over: https://192.168.10.20/nagios just not https://192.168.10.20/viewvc
However, i am able to access viewvc over HTTP: 192.168.10.20/viewvc
iptables, firewalld and selinux are disabled for testing purposes

**Comment by cmpilato** [comment]
ViewVC is just a CGI script -- pretty lightweight in terms of configuration at the Apache level.  I can't think of any reason why it would not be accessible via SSL unless something about that VirtualHost has CGI disabled, or isn't granting access to the <Directory> in which ViewVC's code is housed, or any number of other little things that are just as likely to cause problems for non-SSL deployments.  If you are able to share specific configuration bits, that might help someone spot a problem.

**Comment by did8** [comment]
Sorry for the delay in response. I was not able to get it working with ViewVC. However, i was able to get it working with cvsweb. Same apache virtual host config and it worked immediately. Not really a big issue now since it's resolved.
Thank you for your reply.
