### ISSUE TITLE
ViewVC Running Time As Function of Number of Commits in SVN Repository?

### ISSUE THREAD

**Issue by dtashley** [viewvc/viewvc#155]
I have a Lenovo 11e (elementary school laptop) acting as my web and version control server.  The machine is slow, but it has the advantage that it draws less than 10 Watts so my annual power cost is less than $15.

My SVN repository only has about 200 commits,  ViewVC works fine.

But I'm curious … as the number of commits gets larger (lets say 10,000 or 100,000) … will browsing the SVN repository get slower?  Is SVN O(n), O(log n), what?  Has anyone had experience with SVN repositories with a lot of commits?

I'm only concerned because I have a VERY slow server.

**Comment by sayhurtz33** [comment]
Whats this mean?

**Comment by cmpilato** [comment]
Subversion itself was designed to scale to large numbers of commits.  It doesn't get slower over time, except in cases where it is being asked to operate on data where the depth of the history of an object is being examined.  For example, if you ask SVN to show all the log messages for commits in the repository, it will obviously take longer to fetch and display that information for 10,000 commits than for 10.  Or if you are viewing line-based annotations on a large file that sees many changes to varied lines within it, it can take longer to gather all the revision metadata required to display that final collated display of information.

ViewVC's performance when viewing Subversion repositories is analogous to Subversion's own.

For an example of a fairly long-historied Subversion repository being served by ViewVC, see the Apache Software Foundation's repository at http://svn.apache.org/viewvc/. (Though, I would discourage you from click the revisions next to any directories in that repository. For some reason, the ASF doesn't seem to be using ViewVC's pagination feature for revision logs.)
