### ISSUE TITLE
Feature: Different icon for binary files + add config "cfg.options.download_directly"

### ISSUE THREAD

**Issue by danielmarschall** [viewvc/viewvc#166]
When I am clicking through the files in a repository where the download option is enabled, I accidently download files very often. Because clicking the file name means "download" for binary files, and "view markup" for text/code files. So I would like to suggest two changes:

First, there could be another pictogram so you can easily see which file is code and which file is binary.

Second, there could be a configuration switch which does the following: If you click a binary file, then you will always go to the markup view (you might want to enable define hide_binary_garbage in the template). In the markup view, you can see file/revision properties (which you could not see if you had downloaded the file when you clicked the filename), and can download the file explicitly by clicking download in the markup view.

Here is a patch I have written. Can somebody please create a PullRequest?

(1) Create a 16x16 pictogram templates/default/docroot/images/binary.png.

(2) Apply follow patch:

```
diff -U 2 -r viewvc_original/conf/viewvc.conf.dist viewvc/conf/viewvc.conf.dist
--- viewvc_original/conf/viewvc.conf.dist	2018-11-01 11:06:14.824994030 +0100
+++ viewvc/conf/viewvc.conf.dist	2018-11-02 18:10:17.305992089 +0100
@@ -349,4 +349,15 @@
 [options]
 
+## False: In the directory view, clicking a binary file directly leads to its download.
+## True: In the directory view, clicking the file leads to the markup view, where the file properties can be shown, and the file can be downloaded
+##       If set to true, you should set "define hide_binary_garbage" to "1" in temples/default/file.ezt and include "co" in "allowed_views"
+download_directly = 0
+
 ## root_as_url_component: Interpret the first path component in the URL
 ## after the script location as the root to use.  This is an

diff -U 2 -r viewvc_original/templates/default/directory.ezt viewvc/templates/default/directory.ezt
--- viewvc_original/templates/default/directory.ezt	2018-11-01 11:06:14.844993745 +0100
+++ viewvc/templates/default/directory.ezt	2018-11-01 23:40:06.976438012 +0100
@@ -58,10 +58,10 @@
  [end]
 [for entries]
-  [define click_href][is entries.pathtype "dir"][entries.view_href][else][if-any entries.prefer_markup][entries.view_href][else][entries.download_href][end][end][end]
+  [define click_href][is entries.pathtype "dir"][entries.view_href][else][is cfg.options.download_directly "1"][if-any entries.prefer_markup][entries.view_href][else][entries.download_href][end][else][entries.view_href][end][end][end]
 
   <tr class="vc_row_[if-index entries even]even[else]odd[end]">
-    <td style="width: 200px" [if-any click_href]onclick="jumpTo('[click_href]')"[end]>
-    [if-any click_href]<a name="[entries.anchor]" href="[click_href]" title="[is entries.pathtype "dir"]View Directory Contents[else][if-any entries.prefer_markup]View[else]Download[end] File Contents[end]">[end]
-       <img src="[docroot]/images/[is entries.pathtype "dir"]dir[else][is entries.state "dead"]broken[else]text[end][end].png" alt="" class="vc_icon" />
+    <td style="width: 200px" [if-any click_href]onclick="jumpTo('[click_href]')"[end]>
+    [if-any click_href]<a name="[entries.anchor]" href="[click_href]" title="[is entries.pathtype "dir"]View Directory Contents[else][is cfg.options.download_directly "1"][if-any entries.prefer_markup]View[else]Download[end][else]View[end] File Contents[end]">[end]
+       <img src="[docroot]/images/[is entries.pathtype "dir"]dir[else][is entries.state "dead"]broken[else][if-any entries.prefer_markup]text[else]binary[end][end][end].png" alt="" class="vc_icon" />
        [entries.name][is entries.pathtype "dir"]/[end][if-any click_href]</a>[end][if-any entries.lockinfo]<img src="[docroot]/images/lock-icon.gif" alt="locked" class="vc_overlay" title="Locked by [entries.lockinfo]" />[end]
        [is entries.state "dead"](dead)[end]
```

**Comment by cmpilato** [comment]
I've introduced the unique icon bit of this on `master` and backported to `1.1.x`.

I confess I don't love the new configuration option.  Every new option comes with a maintenance cost for development and a mental cost for administrators.  As an aside, the sense of the suggested option seems reversed.  I would expect that `direct_download = 1` (True) would "directly lead[s] to its download" (per the documentation).  I'm guess that was just a brain-o, though.

**Comment by danielmarschall** [comment]
Yes, I seem to have accidentally swapped true and false.

I agree that there shouldn't be too much configuration switches, but in this case I think a lot of people might agree or disagree wth the behavior.  I personally am annoyed if I click something and accidentally download something.  But others might exactly want to download it right away (like it is now).

**Comment by danielmarschall** [comment]
I wonder, is there anything to consider about direct_download if co is not inside allowed_views? (Like, does the co page needs to be "unlocked" first, like you proposed for viewable images in #180 ?)

**Comment by cmpilato** [comment]
To be clear, I don't intend to accept the `direct_download` option (and will be closing this issue after issuing this comment, having accepted the binary icon bit of it).  But yes, the ViewVC code will disallow any "checkout" view when `co` is not in the list of `allowed_views`.
