### ISSUE TITLE
CGI Generic SQL Injection (blind)

### ISSUE THREAD

**Issue by iisinfrastructure** [viewvc/viewvc#170]
Hi,
We use **viewvc 1.1.26** with Rancid & CVS. 
To stay PCIDSS compliant we scan web servers with Tenable Nessus security.
Nessus say that viewvc presents affected CGI script to CGI Generic SQL Injection (blind):

> Using the GET HTTP method, Nessus found that :
> 
> + The following resources may be vulnerable to blind SQL injection :
> 
> + The 'annotate' parameter of the /viewvc/C3_Commutateurs/.cvsignore CGI :
> 
> /viewvc/C3_Commutateurs/.cvsignore?r2=text&diff_format=h&logsort=cvs&pat
> hrev=&r1=1.1&view=log&tr2=1.1&tr1=1.1&revision=1.1&annotate=1.1'||'text&
> diff_format=h&logsort=cvs&pathrev=&r1=1.1&view=log&tr2=1.1&tr1=1.1&revis
> ion=1.1&annotate=1.1
> 
> -------- output --------
> HTTP/1.1 200 OK
> -------- vs --------
> HTTP/1.1 400 Bad Request
> ------------------------
> 
> + The 'tr2' parameter of the /viewvc/C3_Commutateurs/.cvsignore CGI :
> 
> /viewvc/C3_Commutateurs/.cvsignore?r2=text&annotate=1.1&diff_format=h&lo
> gsort=cvs&pathrev=&r1=1.1&view=log&tr1=1.1&revision=1.1&tr2=1.1'||'text&
> annotate=1.1&diff_format=h&logsort=cvs&pathrev=&r1=1.1&view=log&tr1=1.1&
> revision=1.1&tr2=1.1
> 
> -------- output --------
> HTTP/1.1 200 OK
> -------- vs --------
> HTTP/1.1 400 Bad Request
> ------------------------

I think it's false positive, perhaps you have any solutions to protect on that.

Regards,

**Comment by futatuki** [comment]
Hi,
It seems that the response "HTTP/1.1 400 Bad Request" is a result of query string validation (i.e. ViewVC detected crafted query), so I think it is not vulnerable.

**Comment by danielmarschall** [comment]
The "400 bad request" error comes from the Exception handler of ViewVC.
The exact error message is "An illegal value was provided for the "annotate" parameter."

This error message comes from the functions
	lib/viewvc.py:_validate_param(name, value)
and
	lib/viewvc.py:def validate_query_args(request)
	
So in these cases, the HTTP 400 error is safe and wasn't caused by a SQL injection.

An SQL injection can IIRC only happen in lib/viewvc.py:view_query(request). I am not quite sure if the code is safe.

**Comment by cmpilato** [comment]
@danielmarschall Thanks for sorta triaging this report.  You are correct about the cause of the `400 Bad Request`.  I know, too, that the cvsdb code does perform some escaping of "LIKE" parameters (see `lib/cvsdb.py:EscapeLike()`), but all this code predates me.  Reading it now, I think perhaps that code could stand to be tweaked just a bit.  Aren't the square bracket characters also something that should be escaped?  I'm thinking this change is needed:

```python
-_re_likechars = re.compile(r"([_%\\])")
+_re_likechars = re.compile(r"([\[\]_%\\])")
```

Would anyone agree?

**Comment by futatuki** [comment]
If assume we use MySQL only, square bracket characters is not special character for 'LIKE' operator. 
MySQL 4.1:
http://ftp.nchu.edu.tw/MySQL/doc/refman/4.1/en/string-comparison-functions.html#operator_like
MySQL 8.0:
https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html#operator_like
(...and newer MySQL supports new operator 'RLIKE' which allows to search with regular expression. with this, I don't think MySQL will extend 'LIKE' operator in future.)

For some other DBMS, they can be used for special character.
e.g. Microsoft SQL-Server
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-2017

**Comment by futatuki** [comment]
>For some other DBMS, they can be used for special character.

 As far as I can find,  DBMS using extension to use square bracket as special usage for 'LIKE' operator DBMS are only Sybase's and MS's.  At least, It seems that Oracle, Postgress, and SQLite don't support it.

**Comment by cmpilato** [comment]
ViewVC claims to support only MySQL, though perhaps MariaDB is also an option.  So it sounds like the current escape code is sufficient.  Thanks, @futatuki.
