### ISSUE TITLE
FYI: Docker images

### ISSUE THREAD

**Issue by cmanley** [viewvc/viewvc#179]
FYI, I made 2 Docker projects to run ViewVC in containers:
This uses Debian Stretch-slim as base image:
https://github.com/cmanley/viewvc-docker
This is an Alpine 3.8 based branch:
https://github.com/cmanley/viewvc-docker/tree/alpine
The latter is only 10MB smaller (not much of a gain), but has a more complicated Dockerfile in that it needs to compile more dependencies.

I use it for CVS only and ViewVC works well in the way that it scans for all the CVS repositories under a single directory tree.
With SVN however, the behaviour seems different: it doesn't seem to scan subdirs for CVS repositories the same way as it does with CVS. This could be something that needs tweaking if you use svn.

P.S. I've also 'dockerized' it's ancestor: cvsweb.

**Comment by cmpilato** [comment]
@cmanley This is pretty cool.  One think you might consider doing is ditching the use of `cvs_roots` and `svn_roots` configuration, and instead using the `root_parents` approach, which gives that scanned-subdir effect you're looking for.

    root_parents = /opt/svn : svn,
                   /opt/cvs : cvs

**Comment by cmpilato** [comment]
@cmanley You probably also want to pull in the `python-subversion` package, without which ViewVC can't support Subversion at all.

**Comment by cmanley** [comment]
Thanks. I'll add the python-subversion to the master branch. I missed that one. I did include py-subversion in the alpine branch though so it should work there.
I tried using root_parents, but what happened was that CVS and SVN repositories were mixed together under the same root "/". That may work, but I can imagine it being problematic when users have same named repositories both in CVS and SVN (e.g. after a migration).

**Comment by cmanley** [comment]
I've pushed the changes to GitHub, and new Docker images (on Docker Hub) are ready:
https://hub.docker.com/r/cmanley/viewvc/builds/

**Comment by cmpilato** [comment]
@cmanley Do you intend to maintain these images going forward?  I ask because, if so, I'd be happy to drop a note into our README pointing folks your direction who might be looking for Docker image.  (And then I can close this issue.)

**Comment by cmanley** [comment]
Yes, that's my intention.

**Comment by cmpilato** [comment]
Pointers added.  Closing this.
