### ISSUE TITLE
make-database missing quotation for username and password when passing to shell

### ISSUE THREAD

**Issue by owendelong** [viewvc/viewvc#182]
Any username or password which contains shell metacharacters can cause unexpected behavior.

In the version I'm running (CentOS package viewvc-1.1.26-1.el7.noarch), the problem is at line 332 and can be easily corrected by placing single quotes around the two instances of '%s' as follows.

`cmd_args = "--user='%s' --password='%s'" % (username, password)
`

While this doesn't address the security implications and broader issues of the fact that this script doesn't sanitize its input (referenced in another bug), it will, at least allow people to use valid secure passwords that contain characters which would otherwise cause the script to malfunction. It would also help prevent (though possibly not eliminate) unsanitized input from being passed to the shell directly.

I'll also update the file in question in the repository and submit it as a pull request.

**Comment by futatuki** [comment]
Hi, my PR #161 (for master) and #160 (for 1.1.x) aims to fix it,  following guidline in Hacking.md https://github.com/viewvc/viewvc/blob/master/notes/HACKING.md#security
(this issue is same as #141)

I also make another version for newer Python , using subprocess.Popen. 
(https://github.com/futatuki/viewvc/blob/python3_support_with_altsvn/bin/make-database)

**Comment by futatuki** [comment]
> Unfortunately fixing this only exposes other bugs -- cvsdbadmin also fails with such passwords. 

`cvsdbadmin` and `svndbadmin` uses user name and password specified in `viewvc.conf`, and it seems it perform no special transform except trimming preceeding and trailing white spaces and % word expansion (i.e. password start with (and/or end with) white spaces can't handle). If you are quoting password in `viewvc.conf,` dequoting it may solve it.

As far as I tried  password contains !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~  and these except % can be used without quote or escape in `viewvc.conf`.  '%' character is a special  in config file, so it must escape by using %%.

**Comment by cmpilato** [comment]
PR #198 from @futatuki addresses this issue and has been merged to `master`.  I'm closing this now, but note that I am strongly considering bumping the minimal Python requirement in `1.1.x` to allow backporting this (and other) valuable fixes.
