### ISSUE TITLE
What stops us from releasing 1.1.27

### ISSUE THREAD

**Issue by ooxi** [viewvc/viewvc#191]
Current up to date ViewVC instances are running 1.1.26, which contains a *Powered by ViewVC 1.1.26* branding linking to http://viewvc.tigris.org/

This page in turn looks defunct at first, then referring to this GitHub repository, which has not released a new version in over two years.

This is really not a good sign :-(

How about releasing master as 1.1.27? Or at least release 1.1.26.1 with an updated *Powered by* branding :-)

**Comment by cmpilato** [comment]
I hear ya. `master` won't be released as anything but 1.2.0 -- it's the `1.1.x` branch that's carrying 1.1.27-to-be. But I agree, it's been too long since a release. I'll try to make this happen in the next week or so. Counting on you to keep me honest!

**Comment by cmpilato** [comment]
...And it's been a month without anybody keeping me honest!  (I clearly never got around to doing this.)

**Comment by cmpilato** [comment]
Releasing 1.1.27 today.
