### ISSUE TITLE
cvsgraph link broken in README.md

### ISSUE THREAD

**Issue by peterdd** [viewvc/viewvc#194]
http://www.akhphd.au.dk/~bertho/cvsgraph/
seems to be gone, this seems last version on waybackmaschine:
https://web.archive.org/web/20181010101325/http://www.akhphd.au.dk/~bertho/cvsgraph/

**Comment by cmpilato** [comment]
I've attempted to contact the author of that software (who I don't know personally, and whose possible email address I had to spelunk around the Internet for) to see if there's a new canonical location for it.  Fingers crossed.

**Comment by peterdd** [comment]
Debian seems to maintain cvsgraph 1.7.0 for their distributions:

https://packages.debian.org/search?keywords=cvsgraph&searchon=names&suite=all&section=all

just in case ..

**Comment by cmpilato** [comment]
I've removed the link from the README.md, and noted in INSTALL that the website is "formerly at ...".
