### ISSUE TITLE
Bump ViewVC Python requirements

### ISSUE THREAD

**Issue by cmpilato** [viewvc/viewvc#199]
Since assuming the maintenance responsibility for ViewVC, I've tried to make the minimal number of disruptive changes to the various version lineages.  And so we find ourselves with that latest blessed release (from the 1.1.x branch) still declaring that they'll work fine for CVS-only deployments with a Python as old as 1.5.2, and for those serving up Subversion repositories, Python 2.0.  These versions of Python are _ridiculously_ old.  Like, **20 years** old.

And then yesterday I came across this plea:  https://snarky.ca/stop-using-python-2-6/

With that post in my head, plus the version requirements of some of the recent pull requests landing here lately, I found myself asking:  How disruptive would it be to bump the `1.1.x` Python requirements to say, Python 2.7 (which itself drops out of support next year in 2020)?  Or at _least_ Python 2.4, which is "only" almost 15 years old but has a good number of things that I've come to expect from Python.

I think the entirety of `lib/compat.py` would go away, we could use string functions instead of literally using `string.foo(some_string, ...)`, we wouldn't to call out specific Python requirements for CVS or Subversion, etc.  And more importantly, we could actually come _closer to_ testing that the minimal requirements we specify still make sense.  (I think even my oldest machines have Python 2.6 or 2.7 as their base Python version.)

Are there any operating systems left in the 90th percentile of use that don't ship with or at least provide an option for Python 2.7?

**Comment by cmpilato** [comment]
@futatuki @gstein @danielmarschall As folks with recent contributions or historical investments here, any opinions on the matter?

(I know @futatuki would love to see a fully Python3-compatible ViewVC, but that's essentially hinged to Subversion unless we take that integration in a similar direction as the `bincvs` stuff, shelling out to the Subversion command-line client for everything.  But I'd prefer to keep that as a separate conversation that applies to Python 1.2.0 (`master`) only for now ... just too big a change for me to feel comfortable with in `1.1.x`.

**Comment by kfogel** [comment]
FWIW, recapping a phone discussion @cmpilato and I just had: I think it totally makes sense to bump the dep reqs to Python 2.7 (and if that means taking the ViewVC version numbers to 1.2.x that's fine) simply to make maintainers' and contributors' lives easier.  After all, it's not going to cause any real difficulties for OS distributions -- they all already have Python 2.7, and upgrading their ViewVC package will be a matter of changing one number in a config file somewhere and re-assembling the package.

**Comment by futatuki** [comment]
For `1.1.x,`  bumping minimal support version to 2.4 is reasonable to make it easear to review and/or to test. I know there are some reasons to use old environment even if support of OS vendors/distributors are ended, in such case, so I also don't think dropping support for older environment easily.

On the other hand, some OS/distros are now preparing to drop support for Python 2 slowly, but certainly. So I want to add support Python 3 in `master`  and it requires to drop Python < 2.6 support for syntactially incompatibilities. (I already dropped `lib/compat_*.py,`  and it remains to use `lib/popen.py` only in `bin/standalone.py` and `tests/vclib/co.py` in my branch for Python 3 support, though it is still needed to refine and review to make PR).

**Comment by gstein** [comment]
Thanks for asking, @cmpilato!

At this point in time, it makes total sense to move to Python 2.7 as the requirement for 1.2.x. No prior Python versions. It is not an obstacle on any platform, to deploy 2.7.

Should a user desire to use an earlier Python, they can stick to 1.1.x and forego future ViewVC work.

While Python 3.x might be interesting, invoking the command line tool would be rough on high-traffic sites. For svn.apache.org, and the spam load that we see ... in-process libary calls are very important.

**Comment by futatuki** [comment]
> While Python 3.x might be interesting, invoking the command line tool would be rough on high-traffic sites.


I agree it.  Actually I implemented command line 'svn' based driver for vclib as PR #185, it takes very costly on resources.  I think svn_repos <<< svn_ra << svn_commandline if repos are local. It might be only for fallback for internal use, not to use for public services.

**Comment by cmpilato** [comment]
Thanks, all.  This is really valuable feedback.

I've been looking over the list of things that have been added to `master` but not backported to `1.1.x` over the years, and I don't see anything there I woudn't be willing to ship with today in a new version lineage of ViewVC.  So here's what I'm thinking:

- Branch `master` as `1.2.x`.
- Change `1.2.x`'s `__version__` to `1.2.0-dev` (from `1.2-dev` ... it's a small thing).
- Change `master`'s `__version__` to `1.3-dev`.
- Bump the minimum Python on `1.2.x` to Python 2.7.
- Changing nightly script tooling to do the right thing as regards the new version arrangement.
- Declare that `1.1.x` will receive only security fixes in the future.
- Bury `1.0.x` in the ground finally and forever.
- Qualify the new `1.2.x` with an eye on a relatively quick release of `1.2.0`.

The question then remains as to what to do about the Python version requirements for `master` / ViewVC 1.3.  Obviously, the minimum Python should be _at least_ 2.7 there.  But do I go ahead and declare that ViewVC 1.3 will be Python 3-based?  This feels wrong for two big reasons:

1. It's almost like un-supporting Subversion.  I know I could take PR #185, but I really don't _want_ to ever release a ViewVC that supports Subversion via that option alone.  That would almost feels like playing back ViewCVS's history in reverse. :smile:
2. There are other really user-disruptive changes that can (and arguably should) be done in the next big ViewVC version that have exactly nothing to do with Python versions.  The prime example that comes to mind is the commit database feature, which really should get the phoenix treatment (we torch that suckers and see what rises from the ashes) and get re-thunk to handle Subversion as a first-class citizen.

So, I lean toward bumping `master` / 1.3 to require Python 2.7 still for now.  But of course, if the Subversion community (or, ahem, @futatuki working therein) makes Python 3 language bindings a reality soon enough, _then_ I'm more than happy to take `master` there.

**Comment by gstein** [comment]
Over the next few years, despite the EOL of 2.7 ... do you expect "no, we won't ship 2.7" ? I believe the answer is that 2.7 will be available for at least 5 years, regardless of stated EOL. Hopefully, during that time, the svn bindings can catch up.

It also seems possible to make PR#185 an optional shim -- take the performance hit, if you really want Python 3.x.

**Comment by cmpilato** [comment]
Ok.  Well, given that `master` is always experimental and unsupported in this project, I'll bump it to 2.7 for now with the option to move to Python 3 in the future sans ceremony should that make sense.

**Comment by cmpilato** [comment]
And now, this has all been done (except for the inaugural 1.2.0 release.
