### ISSUE TITLE
SubversionException: 160043 - Expected FS format between '1' and '7'; found format '8'

### ISSUE THREAD

**Issue by clemens68** [viewvc/viewvc#201]
as explained here https://github.com/cmanley/viewvc-docker/issues/2

When we try to connect to our subversion repository we see the following python stacktrace:

```
An Exception Has Occurred
Python Traceback
Traceback (most recent call last):
  File "/usr/lib/viewvc/lib/viewvc.py", line 4855, in main
    request.run_viewvc()
  File "/usr/lib/viewvc/lib/viewvc.py", line 276, in run_viewvc
    self.repos.open()
  File "/usr/lib/viewvc/lib/vclib/svn/svn_repos.py", line 387, in open
    self.repos = repos.svn_repos_open(self.rootpath)
  File "/usr/lib/python2.7/dist-packages/libsvn/repos.py", line 261, in svn_repos_open
    return _repos.svn_repos_open(*args)
SubversionException: 160043 - Expected FS format between '1' and '7'; found format '8'
```

"Old" libsvn version?

**Comment by cmpilato** [comment]
Yes, that would seem to be the case.  It would seem that there's a version mismatch between the version of the Subversion libraries (libsvn_repos, libsvn_fs, etc.) which created and manage your repository outside of ViewVC, and those which (via their inclusion by or linkage with the Subversion Python modules) are trying to read data from that repository when access via ViewVC.

**Comment by clemens68** [comment]
does viewcv come with it's "own" subversion lib (.so), or does it try to dock (SWIG) to the "installed" subversion lib

**Comment by cmpilato** [comment]
ViewVC does not provide the Subversion libraries. It's simply uses the `import` syntax to load whatever Subversion Python modules may be found in the Python library path.

**Comment by cmpilato** [comment]
I guess I should be more clear. ViewVC itself does not come with any Subversion libraries. But you originally reported this issue against the ViewVC Docker container. While I'm not familiar with that container, I imagine that it _does_ include some version of those libraries (so that it works "out of the box" when viewing Subversion repositories). So I am reasonably confident that what you are describing is not so much a bug in any one piece of software as the result of multiple layers which attempt to provide some sort of Subversion interactivity doing so with mismatched versions of Subversion's libraries.

**Comment by Zmeydimasik** [comment]
> as explained here https://github.com/cmanley/viewvc-docker/issues/2
> 
> When we try to connect to our subversion repository we see the following python stacktrace:
> 
> ```
> An Exception Has Occurred
> Python Traceback
> Traceback (most recent call last):
>   File "/usr/lib/viewvc/lib/viewvc.py", line 4855, in main
>     request.run_viewvc()
>   File "/usr/lib/viewvc/lib/viewvc.py", line 276, in run_viewvc
>     self.repos.open()
>   File "/usr/lib/viewvc/lib/vclib/svn/svn_repos.py", line 387, in open
>     self.repos = repos.svn_repos_open(self.rootpath)
>   File "/usr/lib/python2.7/dist-packages/libsvn/repos.py", line 261, in svn_repos_open
>     return _repos.svn_repos_open(*args)
> SubversionException: 160043 - Expected FS format between '1' and '7'; found format '8'
> ```
> 
> "Old" libsvn version?
