### ISSUE TITLE
File "/usr/tmp/viewvc-1.1.26/bin/cvsdbadmin", line 55     except cvsdb.error, e:                       ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by eddigrondaia** [viewvc/viewvc#202]
Hi,

during the build of viewvc database, I found the following error:

*~]# /usr/tmp/viewvc-1.1.26/bin/cvsdbadmin rebuild /var/CVS/CVSROOT/
  File "/usr/tmp/viewvc-1.1.26/bin/cvsdbadmin", line 55
    except cvsdb.error, e:
                      ^
SyntaxError: invalid syntax

i'm using fedora 31

can anyone help me?

Thanks

**Comment by cmpilato** [comment]
Is your system running Python 3?  The "except Exception, var" syntax is a Python 2 thing that Python 3 doesn't like.  But to be clear, ViewVC is advertised to work only with Python 2 right now.

**Comment by eddigrondaia** [comment]
@cmpilato thanks for your feedback. My default version is 2.7.17.

**Comment by cmpilato** [comment]
Hrm.  I don't see this, even with Python 2.7 explicitly referenced in the script's shebang line:

> #!/usr/bin/env python2.7

What happens if change that line locally to be more Python3-esque?

> except cvsdb.error as e:

?

**Comment by cmpilato** [comment]
Closing this due to lack of OP response.  @eddigrondaia feel free to reopen if this is still an issue for you.
