### ISSUE TITLE
CGI mode fails to transmit binary artifacts (template images, etc.)

### ISSUE THREAD

**Issue by cmpilato** [viewvc/viewvc#219]
ViewVC running in CGI mode is currently failing to transmit any binary artifacts.  These include template images (passed through from `view_doc()`) and binary versioned files (via `view_checkout()`).  The following error is rendered in the logs:

```
Traceback (most recent call last):
  File "/opt/viewvc/lib/viewvc.py", line 5236, in main
    request.run_viewvc()
  File "/opt/viewvc/lib/viewvc.py", line 196, in run_viewvc
    return view_doc(self)
  File "/opt/viewvc/lib/viewvc.py", line 3255, in view_doc
    content_length=content_length))
  File "/opt/viewvc/lib/viewvc.py", line 1679, in copy_stream
    dst.write(chunk)
TypeError: write() argument must be str, not bytes
```

**Comment by cmpilato** [comment]
These code paths share logic in that they both fetch the SAPI server's `file()` object and then do a stream copy from the file object of the artifact to the server file.  I was able to fix the problem with this patch, but I'm not sure if it's the right thing to do.

Note that I'm flushing sys.stdout after sending the headers because if you don't, they seem to never get sent -- you just get the body of the response without all the headers.

```python
diff --git a/lib/sapi.py b/lib/sapi.py
index 832d7d40..3724159f 100644
--- a/lib/sapi.py
+++ b/lib/sapi.py
@@ -175,12 +175,14 @@ class CgiServer(Server):
 
       sys.stdout.write('%sContent-Type: %s\r\n%s\r\n'
                        % (status, content_type, extraheaders))
+      sys.stdout.flush()
 
   def redirect(self, url):
     if self.iis: url = fix_iis_url(self, url)
     self.addheader('Location', url)
     self.header(status='301 Moved')
     sys.stdout.write('This document is located <a href="%s">here</a>.\n' % url)
+    sys.stdout.flush()
 
   def getenv(self, name, value=None):
     ret = os.environ.get(name, value)
@@ -197,13 +199,13 @@ class CgiServer(Server):
                             keep_blank_values, strict_parsing)
 
   def write(self, s):
-    sys.stdout.write(s)
+    sys.stdout.buffer.write(s)
 
   def flush(self):
-    sys.stdout.flush()
+    sys.stdout.buffer.flush()
 
   def file(self):
-    return sys.stdout
+    return sys.stdout.buffer
 
 
 class WsgiServer(Server):
```

@futatuki Any thoughts on this?

And as an aside, my instinct is that the SAPI interfaces need documentation for their interfaces, explaining their expectations.

**Comment by futatuki** [comment]
> @futatuki Any thoughts on this?

In lib/viewvc.py side,  get_writerady_server_file() expects that request.server.file() returns byte stream and  get_writerady_server_file() itself should return byte stream. However there are some confusion in the caller code while Python 3 porting.

The patch looks good to me.  After sending header, we shuold not use sys.stdout as str stream IO object. 

... and,  obviously bin/standalone.py is incorrectly wrap sys.stdout for Python 3. I think there is no need that StandaloneServer inherit sapi.CgiServer any more, because of difference of their output stream objects.

**Comment by futatuki** [comment]
> ```
>    def redirect(self, url):
>      if self.iis: url = fix_iis_url(self, url)
>      self.addheader('Location', url)
>      self.header(status='301 Moved')
>      sys.stdout.write('This document is located <a href="%s">here</a>.\n' % url)
> +    sys.stdout.flush()
> ```

To clarify that the message 'This document ...' is http body,  it may be better not to use sys.stdout.write() directly by use self.write() after encode the message explicitly (or create new method CgiServer.write_text for this purpose, not to use sys.stdout as io.TextIOwrapperWrapper object).

**Comment by futatuki** [comment]
> ... and, obviously bin/standalone.py is incorrectly wrap sys.stdout for Python 3. I think there is no need that StandaloneServer inherit sapi.CgiServer any more, because of difference of their output stream objects.

I'll make an issue for this.

**Comment by cmpilato** [comment]
I think this is fixed now.  I can run WSGI, CGI and standalone mode side-by-side (using https://github.com/cmpilato/dockerized-viewvc) and see no issues with static binary docs, versioned binary files, etc.
