### ISSUE TITLE
StandaloneServer incorrectly replace sys.stdout in master.

### ISSUE THREAD

**Issue by futatuki** [viewvc/viewvc#220]
As I mensioned in https://github.com/viewvc/viewvc/issues/219#issuecomment-611374858, StandaloneServer class in bin/standalon.py try to replace sys.stdout incorrectly.

https://docs.python.org/3/library/http.server.html#http.server.BaseHTTPRequestHandler.wfile says that http.server.BaseHTTPRequestHandler.wfile is an  io.BufferedIOBase in Python 3.6 and later, which is bytes stream (and even Python 3.x before it seems wfile is also bytes stream), and sys.stdout is usually an io.TextIOWrapper, which is str stream.

As lib/viewvc.py doesn't depend on sys.stdout directly for server output (except CVS annotation view, as far as I read the code),  I think we don't need to replace sys.stdout on StandaloneServer.

This issue may be related to #214 .

**Comment by futatuki** [comment]
> As lib/viewvc.py doesn't depend on sys.stdout directly for server output (except CVS annotation view, as far as I read the code), I think we don't need to replace sys.stdout on StandaloneServer.

It seems CVS annotation view also does not use sys.stdout directly. (I missunderstood use case of lib/blame.py)

> This issue may be related to #214 .

Unfortunately, even if stopping override sys.stdout, #214 is reproduced.

**Comment by futatuki** [comment]
Also it seems no need to replace sys.argv for viewvc.py.

**Comment by cmpilato** [comment]
It's possible that much of this stdio replacing stuff exists because it was necessary long ago with older Pythons and where Python was calling out to many different external binary programs -- feeding them stdio, reading their stdout, etc.  Now that it's, for the most part, a pure Python product, much of that stuff is no longer relevant.

**Comment by futatuki** [comment]
Thanks.  I'll merge issue-220-standalone-server-fix branch, and then close this issue.

**Comment by futatuki** [comment]
Merged.
