### ISSUE TITLE
Beginner, not sure what to do to fix my iPhone?

### ISSUE THREAD

**Issue by cat1112** [viewvc/viewvc#221]
I know that there are files and data missing from my iPhone 8+ iOS 13.4.1 update. It used to be my daughters phone, it’s been factory reset a few times! There’s no Face ID option and App Store sometimes can’t connect to the server. I’ve tried to download apps on tweakbox and it won’t let me. I don’t know how to fix this phone please help!

**Comment by futatuki** [comment]
We are sorry but it is a wrong place to solve your problem. Please contact Apple support.
(see. https://support.apple.com/ )
