### ISSUE TITLE
Unable to install viewvc by specifying --prefix and --destir parameters

### ISSUE THREAD

**Issue by vkratsberg** [viewvc/viewvc#222]
**Describe the bug**
Hi, 
viewvc doesn't install when I try to install it with a 1 liner:

 ./viewvc-install --prefix=/usr/local/viewvc-1.1.28 --destdir=/tmp --clean-mode=true

/usr/loca/viewvc-1.1.28 is not created.

When I run .viewvc-install and follow the prompts, everything works as expected.

**Steps to reproduce the behavior**
Try installing viewvc with 1 liner avoiding prompts:
 ./viewvc-install --prefix=/usr/local/viewvc-1.1.28 --destdir=/tmp --clean-mode=true

**Expected behavior**
Software is expected to be installed in directory specified by --prefix

**Additional context**
Add any other context about the problem here.  Consider attaching any helpful screenshots.

**Comment by futatuki** [comment]
With "`./viewvc-install --prefix=/usr/local/viewvc-1.1.28 --destdir=/tmp --clean-mode=true`",  you were specifying `/tmp/usr/local/viewvc-1.1.28` as install directory. 

DESTDIR path specified by --destdir=DESTDIR, or input from prompt, is not for specifying temporary directory for working while install but path to the "root directory" when application runs.
This is used to make a chrooted environment or installation on exported file system for other system, and so on.

So if you want to install to `/usr/local/viewvc-1.1.28`, you should specify "`./viewvc-install --prefix=/usr/local/viewvc-1.1.28 --destdir='' --clean-mode=true`" instead.

**Comment by vkratsberg** [comment]
Thank you very much for your assistance.  That worked perfectly.

>
