### ISSUE TITLE
Template change in 1.2 branch

### ISSUE THREAD

**Issue by andrewhotlab** [viewvc/viewvc#225]
Hi to all I just upgraded from 1.1.27 to 1.2.1, and the look and feels of the web interface changed from this:

![Screenshot_2020-06-16_13-30-01](https://user-images.githubusercontent.com/26433166/84769311-ea2e0200-afd5-11ea-81c5-edf9e91de66c.png)

... to this:

![Screenshot_2020-06-16_13-30-12](https://user-images.githubusercontent.com/26433166/84769326-f1eda680-afd5-11ea-93de-afe63efe1b89.png)

I'd wish to restore the old "theme" if it's possible, but I do not know how to.

Thanks for any help/suggestion.

**Comment by futatuki** [comment]
You can change default templates to "classic", which is old default templates, by specifying `template_dir = templates/classic` in the `[options]` section in your viewvc.conf file.

Please see [the comment in the default viewvc.conf file](https://github.com/viewvc/viewvc/blob/1.2.1/conf/viewvc.conf.dist#L648) also.

**Comment by andrewhotlab** [comment]
Hi @futatuki, thank you very much for the quick reply!
