### ISSUE TITLE
Which distribution ships ViewVC

### ISSUE THREAD

**Issue by ooxi** [viewvc/viewvc#226]
Could you recommend a distribution shipping ViewVC? Ubuntu unfortunately does not seem to include ViewVC in 20.04 (and 18.04 includes 1.1.26)

**Comment by cmpilato** [comment]
I suspect that the most recent distributions dropped ViewVC because we have yet to officially release a version that supports Python 3.  But it's super-easy to install from source if you wish to do so -- there are no native/compile components that are machine- or distribution-specific.

**Comment by ooxi** [comment]
Thank you for the fast feedback!
