### ISSUE TITLE
Python 3 support for the RCS parsing submodules of rcsparse module

### ISSUE THREAD

**Issue by futatuki** [viewvc/viewvc#232]
The `rcsparse` module can use 3 different parser engine for parsing RCS files.

Here are Python 3 support status for each parser engine modules.

1. `tparse`
The `tparse` module in `misc/tparse`  is not support Python 3 at all, because of difference of C API between Python 2 and Python 3.
2. `texttools`
It seems that the `texttools` module in `ccvs/rcsparse` is a wrapper for a non-standard module `mxTextTools` (TM of eGenix.com), which is a part of [mx Base](https://www.egenix.com/products/python/mxBase/url).  Unfortunately it is not support Python 3, so we may consider to drop support of this.
3. `default` parser
The fall back parser module `default` works on Python 3, as far as the metadata of RCS files don't contain non-ascii characters.  This parser treates parsed metadata as str,  however current implementation uses 'ascii' codecs and 'surrogateescape' error handler for decode them.  Those should be the codec specified by viewvc.conf and error handler suitable to display.

I think at least `default` parser module should be fixed, although use of rcsparse module itself is experimental feature. 

(2020/07/24 fix obvious syntax error on English and the place of texttools module)

**Comment by cmpilato** [comment]
I wish I knew more about the history and usage patterns of these things.  I did quite a bit with rcsparse back when cvs2svn was under active development, but I've never compiled or known anyone who has compile and used tparse.  It's just another one of those things that was in the ViewVC tree (where it honestly never belonged in the first place) that kept sticking around release after release.

Anyway, I'd already made the decision to stop distributing tparse and aspfool in our official tarballs.  Dropping from the repository is the obvious next step, so +1 that that.  And yes, I say we drop texttools, too.

**Comment by futatuki** [comment]
I couldn't find `tparse.cpp` file other than the ViewVC repository, in web search. It is pity to drop tparse module entirely from surface. I'll try to port it to Python 3, a bit, if it still can be used on ViewVC 1.2.1 with Python 2.

**Comment by futatuki** [comment]
It seems it is not easy to port tparse module to Python 3,  because it depends on  PyFile_AsFile() C API and g++ extension to convert  from Python file like object to C++ std::istream.

So +1 to drop tparse support on rcsparse.

**Comment by futatuki** [comment]
Now rcsparse.default.parser works, and support for texttools and tparse submodules is dropped.
Close.
