### ISSUE TITLE
Remove support for mod_python

### ISSUE THREAD

**Issue by futatuki** [viewvc/viewvc#234]
(Brought from https://github.com/viewvc/viewvc/pull/227#issuecomment-656510878 by @futatuki )
> I tried to set up mod_python with Python 3.6 on CentOS 7, however I couldn't. I fixed grisha/mod_python#85 locally, however make test still failed.
> It seems mod_python couldn't find a module specified by PythonHandler directive in httpd.conf.
> 
> So I give up confirming the behaivor of the ModPythonServer.getenv farther more.

(brought from https://github.com/viewvc/viewvc/pull/227#issuecomment-658768091 by @cmpilato)

> SIDEBAR: I, too, am seeing the same issue with mod_python.

For apache httpd, we can use mod_wsgi.  So I think we can drop mod_python safely.

Any thoughts?

**Comment by cmpilato** [comment]
I'm fine with this.

**Comment by cmpilato** [comment]
As a secondary consideration, if we can't verify that ASP support works in Python 3, we should drop that, too.  That would eliminate the last of the ThreadedServer sapi modules, so there's additional code that would go away.
