### ISSUE TITLE
Is a Python 3 release expected soon?

### ISSUE THREAD

**Issue by dlangille** [viewvc/viewvc#236]
Hello,

I would like to update my viewvc 1.2.1 with a version which works with Python 3.

Is a new release expected soon?

Should I take the code as of a certain commit and roll my own? Any particular commit?

Thank you.

**Comment by cmpilato** [comment]
@dlangille Thanks for the gentle prod.  While it's true that we haven't officially released a version of ViewVC with Python 3 support, the `master` branch of this repository implements exactly that.  If you don't mind the idea of running not-yet-finalized-but-also-unlikely-to-drastically-change code, consider grabbing the latest nightly build of ViewVC 1.3.0-to-be from http://viewvc.org/nightly/ (and of course, we'd love to get your feedback on it).

**Comment by dlangille** [comment]
I have a working FreeBSD port installed on FreeBSD 12.1 :)
