### ISSUE TITLE
It seems regular expression literals without raw ("r") prefix cause this. It also causes DeprecationWaring since Python 3.6 and it will be SyntaxError [1].  So I think it is next step that we'll remove W605 from ignore list.

### ISSUE THREAD

**Issue by adilaid** [viewvc/viewvc#239]
It seems regular expression literals without raw ("r") prefix cause this. It also causes DeprecationWaring since Python 3.6 and it will be SyntaxError [1].  So I think it is next step that we'll remove W605 from ignore list.

[1] https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior

_Originally posted by @futatuki in https://github.com/viewvc/viewvc/pull/238#discussion_r541513349_

**Comment by futatuki** [comment]
It was fixed on 6e7b358e9e347c1a3a90649c128be794092ca617.
