### ISSUE TITLE
Ability to highlight lines

### ISSUE THREAD

**Issue by ltog** [viewvc/viewvc#243]
Both Gitlab and Github have the ability to highlight lines for a file of a specific revision. It looks like this (with almost the same syntax):

Gitlab:

https://gitlab.com/inkscape/inkscape/-/blob/0e0fd37e74bcc966c3c8e15fdd7a2f9828744fad/README.md#L6
https://gitlab.com/inkscape/inkscape/-/blob/0e0fd37e74bcc966c3c8e15fdd7a2f9828744fad/README.md#L6-12

Github

`https://github.com/viewvc/viewvc/blob/bd865674967433d1414213b3bcd7112a4e2a2a2c/lib/accept.py#L20`
`https://github.com/viewvc/viewvc/blob/bd865674967433d1414213b3bcd7112a4e2a2a2c/lib/accept.py#L20-L24`

(I write the links to Github lines as code, since these links are automatically converted to "inlined code snippets", like so:

https://github.com/viewvc/viewvc/blob/bd865674967433d1414213b3bcd7112a4e2a2a2c/lib/accept.py#L20-L24

)

Is this possible with ViewVC? If not, I would like to request such a feature. It's a real productivity booster if you can send links to your colleagues that immediately point to the right line(s)! 💪

**Comment by cmpilato** [comment]
ViewVC doesn't have any range support for its file-line handling, but if you click on the line number presented in the file display view, it should link to that particular line using a similar bookmark URL (`#l20`).  From there, decorating such links is just a matter of CSS.  For example, you can add the following to your ViewVC stylesheet in order to make the targeted line show up with a pink background:

```css
.vc_row_even:target td,
.vc_row_odd:target td {
  background-color: pink;
}
```

**Comment by cmpilato** [comment]
Here's an example of this effect (with added animation) I just added to a publicly accessible ViewVC instance:

http://viewvc.red-bean.com/bikeshed/trunk/index.html?revision=28&view=markup#l119

**Comment by ltog** [comment]
@cmpilato : Thank you for the fast and helpful response. The version of ViewVC I'm using doesn't have the ability to click the line number to get a link to it (therefore I didn't discover its syntax), but your CSS seems to work anyway. I'll ask our administrators to add the CSS and maybe update our version.

**Comment by ltog** [comment]
@cmpilato : The CSS change seems to be of general usefulness. Will it be made default in a future version of ViewVC?

**Comment by cmpilato** [comment]
Done.  Thanks for the suggestion!
