### ISSUE TITLE
ViewVC error output HTML is doubly escaped.

### ISSUE THREAD

**Issue by cmpilato** [viewvc/viewvc#257]
When showing an error display, ViewVC is currently doubly-escaping strings, which makes for some challenging reading.

**Comment by cmpilato** [comment]
Does this merit a `CHANGES` entry, or did the problem get introduced since 1.2.x?

**Comment by futatuki** [comment]
At least, it seems that the commit  a087a1873b89d25967065c917f864c3bc0d5c8c7 (HEAD of 1.2.x) does not have this problem, so I think it got introduced after branching 1.2.x.
