### ISSUE TITLE
Error when run viewvc-install

### ISSUE THREAD

**Issue by bendcunha** [viewvc/viewvc#267]
Dear All,

I am installing rancid and and installed it successfully
now i have download viewvc 1.2.1 tar and extract it and when i run viewvc-install i get the below message
---------------
root@rancid viewvc-1.2.1]# ./viewvc-install
  File "./viewvc-install", line 48
    ("bin/cgi/viewvc.cgi",        "bin/cgi/viewvc.cgi",        0755, 1, 0, 0),

-------------------

I am a novice and appreciate your help and advice with the above error

regards

ben
                                                                  ^

**Comment by futatuki** [comment]
Hello,

What is your OS (distribution, version)? And which version of Python do you use?

I think that you tried to use ViewVC 1.2.1 on Python 3.
What is displayed if you do below on your environment?

    `/usr/bin/env python --version`

If you see something like `Python 3.X.Y`, this is the case.
In this case you can use nightly builds snapshot of ViewVC 1.3.0-dev from https://www.viewvc.org/nightly/ instead, although it is not released version.

Alternatively, you can use ViewVC 1.2.1 with Python 2.7, however you need to replace all occurence of "`#!/usr/bin/env python`" with appropriate path to the Python 2.7 interpreter in ViewVC's Python scripts, and also need appropriate libraries for Python 2.7, especially if you want to use rancid with Subversion, you need Subversion Python bindings for Python 2.7.

**Comment by bendcunha** [comment]
Hello Dear
Thanks for the quick reply and apologize my delay
I am using Centos 8 ( 24.18.0-305.10.2.el8_4.x86_64 )
phython installed is Python 3.6.8

So kindly advise

Thanks and apprecite


regards

simon

**Comment by bendcunha** [comment]
Hello dear,

Once again thanks for ur great support . i installed the nightly build and it worked just great


thanks once again

regards

simon

**Comment by bendcunha** [comment]
thanks once again

**Comment by cmpilato** [comment]
Glad it worked for you!
