### ISSUE TITLE
raw view for download/copy configs

### ISSUE THREAD

**Issue by Bl4CkGuuN** [viewvc/viewvc#268]

**Comment by cmpilato** [comment]
Not sure precisely what's being requested here, but ViewVC already offers what it calls the "checkout" or "co" or "download" view, which gives a raw display of human-readable files suitable for downloading or copy-n-pasting file contents.

**Comment by Bl4CkGuuN** [comment]
welp, yeah sorry. My bad!

I upgrade to 1.3.0-dev and forgot that I have to enable it in the viewvc.conf ^^
