### ISSUE TITLE
TypeError exception in ViewVC 1.3.0-dev using authzfile with deny rules

### ISSUE THREAD

**Issue by NMGo** [viewvc/viewvc#277]
**Describe the bug**
Using ViewVC to browse Subversion repositories with [path-based authorisation](https://svnbook.red-bean.com/en/1.7/svn-book.html#svn.serverconfig.pathbasedauthz) is broken as of 1.3.0-dev f97ea6135e45692c5458ef8168ee763312a6807b if deny rules are used.

**Steps to reproduce the behavior**

1. Set up ViewVC to access a Subversion repository with file-based authorisation.
2. In the ViewVC configuration, use the ```authzfile``` option to point to the authorisation rules file.
3. Change the rules file to something like the following:
```
[test:/]
userA = r

[test:/dir1]
userA = rw

[test:/dir2]
userA =
```

The above rules can be summarised as follows: user "userA" has read access to the root of the "test" repository, read-write to "/dir1/" and no access to "/dir2/".

As soon as the user tries to browse to the root of the "test" repository, ViewVC throws an exception (see below). The exception is **not** thrown if ```userA = r``` for the ```/dir2/``` path.

**Expected behavior**
With ViewVC 1.1, the autorisation rules file was handled as expected and "deny" rules were followed. There was no exception thrown.

**Additional context**
Traceback exception after setting ```stacktraces```:
```An Exception Has Occurred
Python Traceback
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 5521, in main
    request.run_viewvc()
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 457, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/viewvc.py", line 2450, in view_directory
    request.repos.dirlogs(request.path_parts, request.pathrev, file_data, options)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/vclib/svn/svn_repos.py", line 497, in dirlogs
    date, author, msg, revprops, changes = self._revinfo(entry_rev)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/vclib/svn/svn_repos.py", line 860, in _revinfo
    cached_info = _revinfo_helper(rev, include_changed_paths)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/vclib/svn/svn_repos.py", line 844, in _revinfo_helper
    found_readable, found_unreadable = _simple_auth_check(fsroot)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/vclib/svn/svn_repos.py", line 802, in _simple_auth_check
    if vclib.check_path_access(self, parts, pathtype, rev):
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/vclib/__init__.py", line 486, in check_path_access
    return auth.check_path_access(repos.rootname(), path_parts, pathtype, rev)
  File "/usr/local/viewvc-1.3.0-dev-f97ea61/lib/vcauth/svnauthz/__init__.py", line 282, in check_path_access
    path = "/" + "/".join(parts)
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by cmpilato** [comment]
[issue-277-recipe.bash.txt](https://github.com/viewvc/viewvc/files/8121024/issue-277-recipe.bash.txt)

**Comment by cmpilato** [comment]
I've attached a bash script that (on my machine, but with an attempt at being at least unix-generic) sets up the problematic scenario and runs standalone.py so it can be observed.

**Comment by futatuki** [comment]
> I've attached a bash script that (on my machine, but with an attempt at being at least unix-generic) sets up the problematic scenario and runs standalone.py so it can be observed.

I confirmed the script works on FreeBSD with ash (/bin/sh on FreeBSD) and PR #279 fixed this issue.

**Comment by NMGo** [comment]
We tested a recent "nightly" (20220418) with -- we believe -- the commit 7c5795c of Feb 24, 2022.

The problem appears to be resolved for us as well. Thank you for fixing this.
