### ISSUE TITLE
Tech Chore: Remove unsupported Subversion compatibility code

### ISSUE THREAD

**Issue by cmpilato** [viewvc/viewvc#280]
As of 1.3.0, the oldest supported Subversion implementation requires version 1.14.0 of Subversion.  But the codebase still has compatibility logic dating back to much, much older Subversion versions.  Let's clean that up.

**Comment by cmpilato** [comment]
Did I already finish this and simply fail to update the issue?

**Comment by futatuki** [comment]
Old compatibility code was already removed, however not all Subversion APIs used by ViewVC are latest ones which is available on Subversion 1.14.x Python bindings (, and some latest, not deprecated, C API are not supported by SWIG Python bindings yet).

**Comment by cmpilato** [comment]
I was never particularly concerned about deprecated Subversion APIs because that community promises ABI compatibility across all 1.* versions.

**Comment by futatuki** [comment]
I see. I warried about overhead of using deperecated APIs caused by compatibility layer in C APIs a bit, however it would be less or equal to preparing parameters to call latest APIs in Python code in most cases.

**Comment by cmpilato** [comment]
If we want to undergo an effort to update all API calls to their latest published forms if only to eliminate a few stack levels, I'm okay with that.

**Comment by futatuki** [comment]
Okey, let us leave them be until newer APIs will be needed for some enhancement like #266, and that is not a mile stone for 1.3.0 release.

**Comment by cmpilato** [comment]
So ... close this issue as complete, and open a new one for "Upgrade use of Subversion APIs to newest versions as of 1.14.0" (with a 3.0.1 milestone)?

**Comment by futatuki** [comment]
Apart from the version number for a milestone, yes.  It would be a part of wish list for developers' side.

**Comment by futatuki** [comment]
I think the reason why we want to ugrade using APIs is not for the program performance but possibility for enhancement supporting newer Subversion's feature.

As I mentioned above,  the performance superiority on reducing overhead of compatibility code would be canceled by overhead for preparing new added constant arguments (creating new Python objects for them) in new API and their conversion in bridging code between Python and C API.

So, if an older API function has enough ability for implementimenting features we need, it might even have advantage that we keep using it.

**Comment by cmpilato** [comment]
I'm going to go ahead and close this.  We can address specific needs (likely to come by way of Subversion features we want to benefit from, if at all) as those needs come into focus.
