### ISSUE TITLE
`svn.core` only available for python 3 in Debian but `standalone.py` is in python 2

### ISSUE THREAD

**Issue by chunjiw** [viewvc/viewvc#287]
In Debian, `svn.core` module is only available from `python3-subversion` package, but `standalone.py` is in python 2 for the latest release 1.2.1. The master branch uses python 3 therefore works.

**Comment by futatuki** [comment]
We won't support Python 2 on 1.2.x branch, and ViewVC for Python 3 is now under development on master branch, as you wrote.

If you regard that Debian does not offer available ViewVC package,  it is not a bug, but just a problem of progress of our project, I think.
 
Please see #138, #236, and #250
