### ISSUE TITLE
ViewVC 1.3.0, Python Error when folders are present in CVS repository: TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by pellepennan** [viewvc/viewvc#288]
ViewVC 1.3.0
Python Error when folders are present in CVS repository:
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

Seems to be related to the function cmp().
def cmp(a, b):
    return (a > b) - (a < b)

As a workaround I changed the function to:
def cmp(a, b):
    if a == None:
        a = 0
    if b == None:
        b = 0
    return (a > b) - (a < b)

When changing the function, the CVS repository can be displayed even with folders present.

**Comment by cmpilato** [comment]
@pellepennan Thanks for the report and solution. Just to clarify, are you seeing this in any repository that has subfolders containing versioned files?  Or is this a repository that has, maybe, empty subdirectories in the repository?

**Comment by pellepennan** [comment]
Hello, I am seeing this in any repository that has subfolders in the "first level"; either empty subfolders or subfolders containing versioned files.
If I remove the subfolders from the "first level", evrything works fine.
It is OK to have subfolders under e.g. the next level, i.e. "second level", that works fine.
It is also possible to access the subfolders under the "first level" if one changes the URI in the browser, although the "first level" folder is not accessible as long as it contains folders.

Some more explaination...
Let us say that the "first level" is a folder named "TEST"
Under TEST there are three folders and one file, one of the folders (firewalls) has a folder (testfolder) now just to test if folders in second level is OK.
TEST/
├── firewalls
│   └── testfolder
├── loadbalancers
│   └── test.txt,v
├── router.db,v
└── webproxy

<SERVER>/viewvc works fine (/viewvc is added as a ScripAlias pointing to /var/www/cgi-bin/viewvc.cgi)
<SERVER>/viewvc/TEST does not work, I get the Python error, however the following works:
<SERVER>/viewvc/TEST/firewalls and also the rest of the folders. i.e. <SERVER>/viewvc/TEST/loadbalancers and <SERVER>/viewvc/TEST/webproxy

If I change the code of viewvc.py a little, i.e. according to my workaround, first level works OK as well.

In version 1.1.28 (Python2) everyting works fine (we use that version at the moment), but in version 1.3.0 (Python3) i came across this problem.
From what I understand, Python3 is more strict in comparision with Python2 in regards to comparing e.g. variables of different data types.
We would like to use 1.3.x, since we want to move away from Python2.

**Comment by pellepennan** [comment]
.. and not sure if my workaround is the best approach, but for now I am happy... :)

**Comment by cmpilato** [comment]
@pellepennan Thanks for the explanation. I wasn't able to reproduce this locally, so I'm guessing there's something interesting about your particular data set.  But I created https://github.com/viewvc/viewvc/pull/289 to implement a slightly more thorough (and universally applied) workaround.

**Comment by pellepennan** [comment]
I added your suggested code and it works perfectly (as was expected).  :)
Many thanks!

**Comment by cmpilato** [comment]
Thanks for the follow-up!  I've merged my PR.

**Comment by futatuki** [comment]
Hello,
I'm starting to read the source to replace the old way of sorting that uses functions for `cmp` keyword with `cmp_to_key()` conversion into native key function, but I can't see where the issue occur, i.e. which parameter of `cmp()` can be `None` in viewvc.py.  @pellepennan , could you please the stack trace with config option `stacktraces = 1` with before fix the issue, if you have still interested in.

**Comment by pellepennan** [comment]
Hello,
I was wondering how to get a more detailed Python Traceback, but now I know how to do it (enable stacktraces), thanks!  :)

With stacktraces enabled, this is what I get:
An Exception Has Occurred
Python Traceback
  File "/usr/local/viewvc/lib/viewvc.py", line 5522, in main
    request.run_viewvc()
  File "/usr/local/viewvc/lib/viewvc.py", line 457, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc/lib/viewvc.py", line 2451, in view_directory
    sort_file_data(file_data, request.roottype, sortdir, sortby, cfg.options.sort_group_dirs)
  File "/usr/local/viewvc/lib/viewvc.py", line 2335, in sort_file_data
    file_data.sort(key=functools.cmp_to_key(file_sort_cmp))
  File "/usr/local/viewvc/lib/viewvc.py", line 2315, in file_sort_cmp
    return file_sort_sortby(file1, file2, sortby)
  File "/usr/local/viewvc/lib/viewvc.py", line 2300, in file_sort_sortby
    return s * cmp(file2.date, file1.date)  # latest date is first
  File "/usr/local/viewvc/lib/viewvc.py", line 98, in cmp
    return (a > b) - (a < b)
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

I use ViewVC together with CVS for RANCID (a set of scripts to handle configuration backups of networking equipment).
To reproduce the error with a new "clean" CVS repository, I create the following example CVS repository:

<SERVER>/viewvc is an alias for <SERVER>/cgi-bin/viewvc.cgi

viewvc.conf:
root_parents = /usr/local/rancid/viewvctest/CVS : cvs

BASE_DIR=/usr/local/rancid/viewvctest
CVSROOT=$BASE_DIR/CVS

export CVSROOT=$CVSROOT
mkdir $BASE_DIR
cvs -d $CVSROOT init

# Create first "level 1 folder"
mkdir $BASE_DIR/level1_1
cd $BASE_DIR/level1_1
cvs import -m "level1_1" level1_1 new level1
cd $BASE_DIR
cvs checkout level1_1

# ViewVC works fine, <SERVER>/viewvc/level1_1/

# Create one more "level 1 folder"
mkdir $BASE_DIR/level1_2
cd $BASE_DIR/level1_2
cvs import -m "level1_2" level1_2 new level1
cd $BASE_DIR
cvs checkout level1_2

# ViewVC works fine, <SERVER>/viewvc/level1_1/ and <SERVER>/viewvc/level1_2/

# Create a file under one level 1 folder
touch $BASE_DIR/level1_1/testfile.txt
cd $BASE_DIR/level1_1
cvs add *
cvs commit -m "level1_1"

# ViewVC works fine, <SERVER>/viewvc/level1_1/ and <SERVER>/viewvc/level1_2/

# Create some level 2 folders under one level 1 folder
mkdir $BASE_DIR/level1_1/{level2_1,level2_2,level2_3}
cvs add $BASE_DIR/level1_1/{level2_1,level2_2,level2_3}
cd $BASE_DIR/level1_1
cvs commit -m "{level2_1,level2_2,level2_3}"

# ViewVC works fine for the level 1 folder that does not have any subfolders (<SERVER>/viewvc/level1_2/), but not for the level 1 folder with subfolders (<SERVER>/viewvc/level1_1/)
# However, if I change the URL to show one level 2 folder under level1_1, e.g. <SERVER>/viewvc/level1_1/level2_1, that works fine

When it does not work, I et the above Python traceback, i.e.:
An Exception Has Occurred
Python Traceback
  File "/usr/local/viewvc/lib/viewvc.py", line 5522, in main
    request.run_viewvc()
  File "/usr/local/viewvc/lib/viewvc.py", line 457, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc/lib/viewvc.py", line 2451, in view_directory
    sort_file_data(file_data, request.roottype, sortdir, sortby, cfg.options.sort_group_dirs)
  File "/usr/local/viewvc/lib/viewvc.py", line 2335, in sort_file_data
    file_data.sort(key=functools.cmp_to_key(file_sort_cmp))
  File "/usr/local/viewvc/lib/viewvc.py", line 2315, in file_sort_cmp
    return file_sort_sortby(file1, file2, sortby)
  File "/usr/local/viewvc/lib/viewvc.py", line 2300, in file_sort_sortby
    return s * cmp(file2.date, file1.date)  # latest date is first
  File "/usr/local/viewvc/lib/viewvc.py", line 98, in cmp
    return (a > b) - (a < b)
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

**Comment by futatuki** [comment]
@pellepennan,  Thank you for your detailed report. I could reproduce the issue.
It could be caused if `sort_by` option is not 'file'. (i.e. the values of `DirEntry.date`, `DirEntry.log`, `DirEntry.author` can be `None` in fucntion `sort_file_data()`  in CVS repository).

And as far as I read the code,  key items for `cmp()`  in other places have no problem (in most place, if they had, another exception had raised before raised in `cmp()`).
