### ISSUE TITLE
viewvc 1.3 markup output lacks formatting

### ISSUE THREAD

**Issue by kberry** [viewvc/viewvc#325]
viewvc 1.1 (and 1.2?) output had various prettifications of the markup output, such as a gray background on the line numbers, making the line numbers right justified (now everything is unaligned after line 99, 999, etc.), a normal html header, `<hr>` between revisions on the log pages, and so on. All of this seems to be gone in 1.3. the output is bare-bones plain. (I installed the nightly build of viewvc-1.3.0-dev-20230429 on a new server running Alma Linux 8, using Subversion 1.14.2, which I built from source.)

Am I missing some configuration option to get the normal marked-up output back? Normally I like bare-bones, but this is a little bare even for me. I tried both current firefox and chrome.

A comparison of the same file shown in 1.3 vs. 1.1:
new: http://new.tug.org/svn/texlive/trunk/Build/source/Build?revision=66136&view=markup
old: https://tug.org/svn/texlive/trunk/Build/source/Build?revision=66136&view=markup

Thanks.

![scr1 3](https://user-images.githubusercontent.com/362855/235316692-bfd02f45-1fe8-4505-af8f-d231e16cabb3.png)
![scr1 1](https://user-images.githubusercontent.com/362855/235316707-0d1659b0-b0f4-4a6d-8289-8eef9712d0ad.png)

**Comment by futatuki** [comment]
It seems that you didn't set up `template_dir` and/or `docroot` option parameters in `viewvc.conf` in new.tug.org.

In http://new.tug.org/svn/texlive/trunk/Build/source/Build?revision=66136&view=markup :
[[[
...
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- ViewVC :: http://www.viewvc.org/ -->
<head>
 <title>[ViewVC] Contents of: texlive/trunk/Build/source/Build</title>
 <meta name="generator" content="ViewVC 1.3.0-dev" />
 <link rel="stylesheet" href="[/viewvc-docroot/styles.css](view-source:http://new.tug.org/viewvc-docroot/styles.css)" type="text/css" />
 <script src="[/viewvc-docroot/scripts.js](view-source:http://new.tug.org/viewvc-docroot/scripts.js)"></script>
 
</head>
<body>
```
...
]]]

view-source:http://new.tug.org/viewvc-docroot/styles.css :
[[[
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```
]]]

**Comment by futatuki** [comment]
Note: Directory layout for template files had been changed between 1.1.x and 1.2.0.

Please see the commit https://github.com/viewvc/viewvc/commit/006b7dc371cf9a1a938206cd4481508ac01f0e3f (2011-10-28).

**Comment by kberry** [comment]
Thanks much. I failed to notice the change as described INSTALL. With
```
Alias /viewvc-docroot "/usr/local/viewvc/templates/default/docroot"
```
all is well.
