### ISSUE TITLE
ImportError: No module named _core

### ISSUE THREAD

**Issue by avhz** [viewvc/viewvc#331]
Hi all, I need a bit of help getting ViewVC back up and running.

ViewVC came packaged and configured along with a different software called FusionForge (it's quite old). 

I upgraded a number of servers from older Debians to Debian 12 recently, and the repository browsing no longer works on our website and returns the following Python traceback:

```bash
Traceback (most recent call last):
  File "/usr/share/___/www/scm/viewvc/lib/viewvc.py", line 3612, in main
    request.run_viewvc()
  File "/usr/share/___/www/scm/viewvc/lib/viewvc.py", line 253, in run_viewvc
    import vclib.svn
  File "/usr/share/___/www/scm/viewvc/lib/vclib/svn/__init__.py", line 25, in <module>
    from svn import fs, repos, core, delta
  File "/usr/lib/python2.7/dist-packages/svn/fs.py", line 26, in <module>
    from libsvn.fs import *
  File "/usr/lib/python2.7/dist-packages/libsvn/fs.py", line 112, in <module>
    import libsvn.core
  File "/usr/lib/python2.7/dist-packages/libsvn/core.py", line 17, in <module>
    _core = swig_import_helper()
  File "/usr/lib/python2.7/dist-packages/libsvn/core.py", line 16, in swig_import_helper
    return importlib.import_module('_core')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _core
```

We are only serving SVN repos, and I have the following packages related to SVN installed:

```bash
fusionforge-plugin-scmsvn
subversion
subversion-tools
python-svn
python3-svn
python-subversion
python3-subversion
```

If anyone has any advice on getting my current installation working again, I'd be very grateful.

NB: I have Googled this already and found some other's with the same issue (some very old posts), and I have tried some of the suggestions such as adding the above locations to PATH and/or PYTHONPATH.

**Comment by futatuki** [comment]
> We are only serving SVN repos, and I have the following packages related to SVN installed:
> 
> ```shell
> fusionforge-plugin-scmsvn
> subversion
> subversion-tools
> python-svn
> python3-svn
> python-subversion
> python3-subversion
> ```

What versions are those ? I don't think that Debian provides packages for Debian 12 which depend on Python 2.  (ViewVC does not need fusionforge-plugin-scmsvn, python-svn, and python3-svn)

If you are using latest subversion package for Debian 12,  it may be same situation as issue #304 (see also the [thread on users@subversion.apache.org](https://lists.apache.org/thread/vcf1p4zz1hh9ndxgcyox322btf0j7dk2).

To get ViewVC work, there are some ways.

- Create a jailed environment to use Debian 10(or older) packages.
- Manually build the Python bindings for Python 2 against installed subversion package
- Manually install (unreleased) 1.3-dev version of ViewVC and use it with latest subversion, subversion-python3 packages built for Debian 12.
- etc...

**Comment by futatuki** [comment]
> python-subversion/now 1.10.4-1+deb10u3 amd64 [installed, local]

This seems a Python 2 bindings for Subversion 1.10.4 (built for Debian 10) , and

> subversion/stable,now 1.14.2-4+b2 amd64 [installed]

is a package of Subversion 1.14.2.  As I mentioned in issue #304 and the thread on users@subversion.apache.org,  old (before Subversion 1.11) Python bindings package cannot work with newer Subversion (than 1.12).

> Will manually building the Python bindings interfere with my current configuration of Subversion and ViewVC ?

If you've never built Subversion from source files manually, it may be hard.

To build Python 2 bindings against subversion/stable,now 1.14.2-4+b2 amd64 package, 

1. Get Apache subversion source files used for built ubversion/stable,now 1.14.2-4+b2 package
2. Read `INSTALL` and `subversion/bindings/swig/INSTALL` in Subversion's source tree. 
3. Prepare software which is needed to build Subversion and its Python 2 bindings (as written in the documents mentioned in step 2.)
4. Do '`./autogen.sh`' on top of Subversion's source tree (as written in the documents mensioned in step 2.).
5. Do '`./configure`' with same options which used when subversion-1.14.2-4+b2 package was built, except the options for building Python 2 bindings.
6. Do '`make swig-py`' (as written in the documents mensioned in step 2.).
7. Install  the files built to right place.
 
As I don't have Debian 12 environ environment to play with (and I don't have an interest in it),  I can't tell you detailed steps.

**Comment by futatuki** [comment]
If you don't need cvsdb (check in database, both for CVS and Subversion) feature,  using 1.3-dev version of  ViewVC is much easier, although you also need to edit your viewvc.conf used for ViewVC 1.1.x, to suitable for ViewVC 1.3-dev.  Latest snap shot of ViewVC 1.3-dev can be found in https://www.viewvc.org/nightly/ (buid of master).

**Comment by futatuki** [comment]
> A quick grep indicates that we do use `csvdb`, how can I confirm this ?
> 
> For this:
> 
> > 7. Install the files built to right place.
> 
> What is the right place ?

It depends on your environment.  The place where your Python 2 interpreter, used by your ViewVC program, can find them.

**Comment by futatuki** [comment]
If you also have some trouble with fusionforge-plugin-scmsvn,  My recomendation is

> - Create a jailed environment to use Debian 10(or older) packages.

Perhaps  "fusionforge-plugin-scmsvn/now 5.3.2+20141104-3+deb8u3" is a package for Debian 8,  so  it might need to build a jailed (chrooted) environment with fusinoforge, fusionforge-plugin-scmsvn and their depended packages including subversion package, with bind mounting repository directory.
   
The reason I insist a jailed environment is that I'm afraid mixing packages for different release branches may cause dependency problems.  Dependency definition in packages sometimes broken and won't fix if the packages are deperecated.

**Comment by futatuki** [comment]
It seems you didn't adjust new template path.  Please  see the closed issue #325.
If it is not your case,  please open new issue and tell us more detail.

**Comment by futatuki** [comment]
> I have `template_dir = templates/default`, is this what you mean ?

Partly, yes. Make sure that  css files are served in your environment.

If you also use `docroot` option in viewvc.conf,  you may need to adjust your web server configuration like  https://github.com/viewvc/viewvc/issues/325#issuecomment-1528873485 .

**Comment by futatuki** [comment]
> Hi sorry for the late reply, I have been away.
> 
> How can I make sure css files are served?

1. Find an url of one of css files used by your ViewVC set up.
   It can be done by viewing HTML source of one of your ViewVC page.
 
2. Get the css file via http(s) from your ViewVC server.

If  they are served correctly, you can see the content of the css file.

> In [#325](https://github.com/viewvc/viewvc/issues/325#issuecomment-1528873485), are they creating a Linux alias or is that something in ViewVC ?

If you are using the `docroot` option,  you need to set up http server to serve static files (including css files) correctly.  Please see ["Direct static document access" section in INSTALL document](https://github.com/viewvc/viewvc/blob/master/INSTALL#direct-static-document-access).

**Comment by futatuki** [comment]
Then,  please open new issue about it.  For the explanation of the problem,  screen shots or html output of the view would be useful.
