### ISSUE TITLE
forbidden repos are shown in the index

### ISSUE THREAD

**Issue by jlusky** [viewvc/viewvc#333]
**Describe the bug**
I just installed 1.3 from git and adapted the config that I was running on 1.2.  When I go to https://svn.ircd-hybrid.org/viewvc/, repos that hidden by my forbidden = line are shown in the listing. 1.2 didn't show them,

![image](https://github.com/viewvc/viewvc/assets/5530840/d8ab51f9-ab5f-40e6-8003-b7cf9d38a649)

![image](https://github.com/viewvc/viewvc/assets/5530840/85a297c2-e4b5-4837-9a9d-4b54973f0cf5)

developers/ and www/ shouldn't be in that listing.

If I click on one of those listings, I get a 404 Not Found:
![image](https://github.com/viewvc/viewvc/assets/5530840/cc0d6127-5e52-4dde-9ccf-50a6db01dc70)

I tried using forbiddenre instead, and couldn't get to block anything except the root.

**Comment by cmpilato** [comment]
I can confirm this, and think I've identified the problem.

**Comment by cmpilato** [comment]
Track fixes for this in https://github.com/viewvc/viewvc/pull/334.

**Comment by jlusky** [comment]
#334 appears to fix my problems with forbidden and forbiddenre authorizers.  Thanks!
