### ISSUE TITLE
Viewvc 1.3.0 nightly build python 3 issue

### ISSUE THREAD

**Issue by dipuharidasan** [viewvc/viewvc#336]
I have been using the viewvc 1.3.0 nightly build version for few months without any issues. The SCM tool that I use is subversion. Recently one of our developers replaced (R) a folder by mistake and committed to svn which ended up removing all the files from that directory. We then reverse merged that commit to bring back the files. Post that viewvc started throwing the below error when we hit the URL like "viewvc/myrepo?revision=revision&view=revision", if the commit is to the replaced and reverted folder.

```
An Exception Has Occurred
Python Traceback
AttributeError: 'str' object has no attribute 'decode'
```

After enabling trace:

```
Python Traceback
  File "/usr/local/viewvc-1.3.0-dev/lib/viewvc.py", line 5562, in main
    request.run_viewvc()
  File "/usr/local/viewvc-1.3.0-dev/lib/viewvc.py", line 459, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc-1.3.0-dev/lib/viewvc.py", line 4456, in view_revision
    request, revprops[name].decode(request.repos.content_encoding, "backslashreplace")
AttributeError: 'str' object has no attribute 'decode'
```

I ended up making the below changes to make this work.

```
dipuh-mbp:viewvc dipuh$ git diff
diff --git a/lib/viewvc.py b/lib/viewvc.py
index b7f44d7f..71a3c872 100644
--- a/lib/viewvc.py
+++ b/lib/viewvc.py
@@ -4453,7 +4453,7 @@ def view_revision(request):
         undisplayable = is_undisplayable(revprops[name])
         if not undisplayable:
             lf = LogFormatter(
-                request, revprops[name].decode(request.repos.content_encoding, "backslashreplace")
+                request, revprops[name].encode(request.repos.content_encoding, "backslashreplace").decode('utf-8')
             )
             value = lf.get(maxlen=0, htmlize=1)
         else:
dipuh-mbp:viewvc dipuh$
```

Could you please help and correct this in the 1.3 release if its relavant?

Thanks,
Dipu H

**Comment by cmpilato** [comment]
@futatuki This needs your eyes, if you have them to spare.  I would have thought that since we've determined that the property value is _not_ undisplayable (which is to say, displayable), the fix here is to avoid transcoding altogether:

```
-            lf = LogFormatter(
-                request, revprops[name].decode(request.repos.content_encoding, "backslashreplace")
-            )
+            lf = LogFormatter(request, revprops[name])
```

We have similar code up in [line 1989](https://github.com/viewvc/viewvc/blob/d07f1961512005f0dd8a94a79e562656c9dc10c8/lib/viewvc.py#L1989).

**Comment by futatuki** [comment]
@cmpilato You are right.

More digging the code, revpops[] here is already  "normalized" which means, theire values are already displayable (unicode) str or binary object which cannot decoded (by the repository specific encoding when I wrote the code for nomarizing, but actually always by 'utf-8').

**Comment by cmpilato** [comment]
Closing this issue as fixed.  @dipuharidasan feel free to reopen if an update to a newer nightly doesn't resolve the problem.
