### ISSUE TITLE
TypeError: 'str' object doesn't support item deletion

### ISSUE THREAD

**Issue by tdereus** [viewvc/viewvc#339]
**Describe the bug**
When using viewvc and clicking on a cvs entry i get the following error:
![image](https://github.com/viewvc/viewvc/assets/3882173/4528591d-7ed1-4887-8ccc-02d05d65ae4c)

![image](https://github.com/viewvc/viewvc/assets/3882173/e008eed8-1616-4233-a6b8-d139dfb16ff6)

**Expected behavior**
shows the contents

I also see this same behaviour when I try to view a revision or any diff

this is on version: 1.2.3
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by futatuki** [comment]
To determine what happened, we need more detailed stacktrace, and/or content of your viewvc.conf.

Could you try again after adding "`stacktraces = 1`" line in "`[options]`" section in your viewvc.conf and show us the Python traceback when the exception occured ?

Also could you show us the result of 
```
egrep -v "^ *($|#)' /path/to/your/viewvc.conf
```
(Of course, replace `/path/to/your/viewvc.conf` with real path to your viewvc.conf)?

**Comment by tdereus** [comment]
logs show:

An Exception Has Occurred
Python Traceback
  File "/usr/local/viewvc-1.2.3/lib/viewvc.py", line 5213, in main
    request.run_viewvc()
  File "/usr/local/viewvc-1.2.3/lib/viewvc.py", line 428, in run_viewvc
    self.view_func(self)
  File "/usr/local/viewvc-1.2.3/lib/viewvc.py", line 2170, in view_markup
    markup_or_annotate(request, 0)
  File "/usr/local/viewvc-1.2.3/lib/viewvc.py", line 2057, in markup_or_annotate
    fp, revision = request.repos.openfile(path, rev, {'cvs_oldkeywords' : 1})
  File "/usr/local/viewvc-1.2.3/lib/vclib/ccvs/ccvs.py", line 156, in openfile
    rcsparse.parse(open(path, 'rb'), sink)
  File "/usr/local/viewvc-1.2.3/lib/vclib/ccvs/rcsparse/__init__.py", line 44, in parse
    return Parser().parse(file, sink)
  File "/usr/local/viewvc-1.2.3/lib/vclib/ccvs/rcsparse/common.py", line 477, in parse
    self.parse_rcs_deltatext()
  File "/usr/local/viewvc-1.2.3/lib/vclib/ccvs/rcsparse/common.py", line 450, in parse_rcs_deltatext
    self.sink.set_revision_info(revision, log, text)
  File "/usr/local/viewvc-1.2.3/lib/vclib/ccvs/ccvs.py", line 405, in set_revision_info
    self.sstext = StreamText(text)
  File "/usr/local/viewvc-1.2.3/lib/vclib/ccvs/ccvs.py", line 338, in __init__
    self.text = _msplit(text)
  File "/usr/local/viewvc-1.2.3/lib/vclib/ccvs/ccvs.py", line 327, in _msplit
    del line[-1]
TypeError: 'str' object doesn't support item deletion

# egrep -v "^ *($|#)" /usr/local/viewvc-1.2.3/viewvc.conf

[general]
root_parents =/usr/local/rancid/var/CVS:cvs
[utilities]
rcs_dir = /usr/bin
[options]
use_rcsparse = 1
stacktraces = 1
[templates]
[cvsdb]
enabled = 1
host = localhost
database_name = ViewVC
user = VIEWVC
passwd = xxxxxxx
readonly_user = VIEWCRO
readonly_passwd = xxxxxx
[vhosts]
[authz-forbidden]
[authz-forbiddenre]
[authz-svnauthz]

**Comment by futatuki** [comment]
Thank you for the detailed information.  (And I'm sorry,  I was not aware that viewvc.conf may contain sensitive data such as access user ID and password for cvsdb).

I'll take a look.

**Comment by futatuki** [comment]
This is a bug of  a compornent CVS repository driver using rcsparse.   I'll continue digging it.

However, it is not a solution, but if you want to use ViewVC without this exception immediately,  you can try another CVS repository driver, by setting `use_rcsparse = 0` in section `[options]` in your viewvc.conf.

**Comment by futatuki** [comment]
It was caused by a typo in PR #274 for the fix of issue #272.

@tdereus Could you try this patch?
```
diff --git a/lib/vclib/ccvs/ccvs.py b/lib/vclib/ccvs/ccvs.py
index 87300736..1c754fa5 100644
--- a/lib/vclib/ccvs/ccvs.py
+++ b/lib/vclib/ccvs/ccvs.py
@@ -324,7 +324,7 @@ def _msplit(s):
 
   lines = [line + '\n' for line in s.split('\n')]
   if lines[-1] == '\n':
-    del line[-1]
+    del lines[-1]
   else:
     lines[-1] = lines[-1][:-1]
   return lines
```
(This is brought from PR #340)

**Comment by futatuki** [comment]
Note: PR #273, the fix of issue #272 in master, did not contain this typo.

**Comment by tdereus** [comment]
@futatuki  - 

The patch to ccvs.py fixes the issue when use_rcsparse=1
The workaround of setting use_rcsparse=0 also works when patch isn't applied.

**Comment by futatuki** [comment]
> @futatuki -
> 
> The patch to ccvs.py fixes the issue when use_rcsparse=1 The workaround of setting use_rcsparse=0 also works when patch isn't applied.

@tdereus Thank you very much for the confirmation.
