### ISSUE TITLE
Pure RCS (not part of CVS repo) no longer supported in ViewVC 1.3.0

### ISSUE THREAD

**Issue by borekl** [viewvc/viewvc#343]
In older ViewVC versions (1.1.26 for sure), directories containing RCS files were supported. You could add such directory as a CVS root and it worked fine (without actual CVS repo). It looks like this is no longer supported, as my directories don't show up anymore.

Or am I missing something?

**Comment by cmpilato** [comment]
I can confirm that ViewVC 1.3 doesn't recognize just a directory of RCS files as a repository.  You need to create a(n empty) file `./CVSROOT/config` in the root of that tree for ViewVC to treat it as worthy of display.

**Comment by borekl** [comment]
> I can confirm that ViewVC 1.3 doesn't recognize just a directory of RCS files as a repository. You need to create a(n empty) file `./CVSROOT/config` in the root of that tree for ViewVC to treat it as worthy of display. (I honestly don't remember how this worked in 1.1, but I have no reason to doubt your description.)

Thanks, this works and the CVS roots now show up in standalone.py. For some reason I still cannot get them work in Apache (the CGI runs, but something is wrong as static files are not served, links don't work and bare unstyled page is shown).

**Comment by futatuki** [comment]
I guess you were served ViewVC 1.1.x and `Alias` directive for static files unchanged. 

Anyways,  please check the consistency between your `template_dir` , `docroot`  settings viewvc.conf  and `Alias` directive in the httpd.conf.

**Comment by borekl** [comment]
As far as I am concerned, this problem is solved for me. The issues I have now are apache issues unrelated to ViewVC.

**Comment by cmpilato** [comment]
Thanks, @borekl.  I'll close this issue, then.
