### ISSUE TITLE
Viewvc 1.3-dev root_parents not showing cvs folders

### ISSUE THREAD

**Issue by alkalinelito** [viewvc/viewvc#348]
Hi, I'm testing viewvc 1.3-dev on a new debian bookworm install.

I only change root_parents option in viewvc.conf:
`root_parents = /sampleCVSpath : cvs`

Then run bin/standalone.py built in webserver, it doesn't show anything:
![image](https://github.com/viewvc/viewvc/assets/62256/400e1a19-98e5-4633-95ce-da705bdf893e)

Same config using old debian install,  viewvc 1.2.3 and it shows correctly the default folder: 
![image](https://github.com/viewvc/viewvc/assets/62256/0dfe9a4d-c477-4c35-b2ae-fd246196786e)

sample cvs folder:
[SampleCVSfolder.zip](https://github.com/viewvc/viewvc/files/15310316/SampleCVSfolder.zip)

**Comment by cmpilato** [comment]
With:
- the latest code in `master`
- your zip archive exploded into `/home/cmpilato/tests/viewvc-test/`
- my `viewvc.conf` file carrying `root_parents = /home/cmpilato/tests/viewvc-test : cvs`
- running `standalone.py --config-file /path/to/viewvc.conf`

...I see the following.

![Screenshot from 2024-05-14 14-49-06](https://github.com/viewvc/viewvc/assets/1846920/8bca6b85-2814-4d77-ac15-0f9614c0e0c8)

**Comment by alkalinelito** [comment]
Hi thanks for your help,

It seems in your test you point to the parent folder (viewvc-test) of the CVS folder.
Tested this on my 1.3-dev install and it works.

If you use this path in v1.2.3 :
`/home/cmpilato/tests/viewvc-test/CVS`
it works,  but doesn't work in 1.3-dev

**Comment by cmpilato** [comment]
Hrm... this is an inconsistency I wouldn't have expected.  Or, I'm just getting old and can't remember anything anymore.

The relevant code carries this comment (in both `1.2.x` and `master`/1.3-dev):

```python
  # Each subdirectory of PARENT_PATH that contains a child
  # "CVSROOT/config" is added the set of returned roots.  Or, if the
  # PARENT_PATH itself contains a child "CVSROOT/config", then all its
  # subdirectories are returned as roots.
```

This reads to me as if your configuration is as valid as mine -- that because your "CVS" directory has a "CVSROOT/config" living under it, then "default" (and other siblings thereof) should show up as roots.

Let me look into this some more.

**Comment by cmpilato** [comment]
Okay, I think I've spotted the issue.  In `1.2.x`, we have this block of code:

```python
class BaseCVSRepository(vclib.Repository):
  def __init__(self, name, rootpath, authorizer, utilities):
    if not os.path.isdir(rootpath):
      raise vclib.ReposNotFound(name) 
```

The corresponding logic for 1.3 is like so:

```python
class BaseCVSRepository(vclib.Repository):
    def __init__(self, name, rootpath, authorizer, utilities,
                 content_encoding, path_encoding):
        if not vclib.ccvs._is_cvsroot(rootpath, path_encoding):
            raise vclib.ReposNotFound(name)
```

Notice that the newer code is asking "Is this really a CVS repository?" whereas the older (consistent with the comment I mentioned previously) asks only, "Is this a directory?"  What remains now is to understand why this logic was changed.

@futatuki Does anything ring a bell here?  It looks like at a minimum this code was one of many places that needed to become encoding-aware, but was the validity test changed to the more aggressive requirement intentionally?

**Comment by futatuki** [comment]
It was the change in the commit 14e7719fe9bd7a8b0002ca17dac0f6910d77f1ac in the pull request #229 , and it seems it is intentional but incorrect assumption of the case where the encoding for the repository is not  file system encoding.

```
@@ -37,7 +37,7 @@ def _path_join(path_parts):
 class BaseCVSRepository(vclib.Repository):
     def __init__(self, name, rootpath, authorizer, utilities,
                  content_encoding, path_encoding):
-        if not os.path.isdir(_getfspath(rootpath, path_encoding)):
+        if not vclib.ccvs._is_cvsroot(rootpath, path_encoding):
             raise vclib.ReposNotFound(name)
 
         self.name = name
```

The code before changed is enough for the purpose.

Anyways, for the consistency to vclib.cvs.expand_root_parent(), this hunk should be reverted or add the check for the case that the parent directory is the cvsroot.

**Comment by cmpilato** [comment]
@futatuki As always, thanks for your insight!  I've posted https://github.com/viewvc/viewvc/pull/349 to address this.

**Comment by cmpilato** [comment]
Closing as fixed, but @alkalinelito feel free to reopen if tomorrow's nightly build doesn't fix this for you.

**Comment by alkalinelito** [comment]
Thanks! , fixed now
