### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by CV-GPhL** [viewvc/viewvc#353]
https://github.com/viewvc/viewvc/blob/7bbda2e81de4db3d7da0a3275e5561a5ce092d43/lib/vclib/ccvs/bincvs.py#L258

should probably be "self.content_encoding" (and not "self.encodig").

**Comment by cmpilato** [comment]
I think `self.encoding` is the correct correction given the rest of the change context in https://github.com/viewvc/viewvc/commit/9e961b9657567f15daea83aafe5dd6a0235f694a, but yes, pretty confident it was a typo.

**Comment by futatuki** [comment]
Ah, yes.  self.encoding was renamed to self.content_encoding in e5c88a3607f857dd8e5f48170cb9e1713cfd7029,  it was not replaced because of typo.

**Comment by futatuki** [comment]
Thank you for the PR.  I've merged it.
