### ISSUE TITLE
Support python3 in install

### ISSUE THREAD

**Issue by robertfetter** [viewvc/viewvc#363]
**Describe the bug**

The install assumes python2, As that is obsolete provide support for python3. Debian 12 does not have python2.

**Steps to reproduce the behavior**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Consider attaching any helpful screenshots.

**Comment by cmpilato** [comment]
@robertfetter Can you add some more details?  When you say "the install" do you mean the `INSTALL` file content, or the `viewvc-install` script, or ... ?

**Comment by gjaekel** [comment]
I yet get notice of _viewvc_, take a look on it and drop it at once.

To my opinion, @robertfetter is pretty clear: Please Provide / migrate to  Python3 because Python2 is EOL for years!

**Comment by futatuki** [comment]
> To my opinion, @robertfetter is pretty clear: Please Provide / migrate to Python3 because Python2 is EOL for years!

If it is so the label "bug" is not suitable, and this issue can be closed because it is already covered by other issues (#138(closed), #250, #310 ; ViewVC 1.3 is for Python 3).
